//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoC.TypedEntities
{
	
	
	#region 
	static
	/// <summary>
	/// Business that represents a customer or potential customer. The company that is billed in business transactions.
	/// </summary>
	public partial class AccountLogicalNames
	{
		
		public const string accountcategorycode = "accountcategorycode";
		
		public const string accountclassificationcode = "accountclassificationcode";
		
		public const string accountid = "accountid";
		
		public const string accountnumber = "accountnumber";
		
		public const string accountratingcode = "accountratingcode";
		
		public const string address1_addressid = "address1_addressid";
		
		public const string address1_addresstypecode = "address1_addresstypecode";
		
		public const string address1_city = "address1_city";
		
		public const string address1_composite = "address1_composite";
		
		public const string address1_country = "address1_country";
		
		public const string address1_county = "address1_county";
		
		public const string address1_fax = "address1_fax";
		
		public const string address1_freighttermscode = "address1_freighttermscode";
		
		public const string address1_latitude = "address1_latitude";
		
		public const string address1_line1 = "address1_line1";
		
		public const string address1_line2 = "address1_line2";
		
		public const string address1_line3 = "address1_line3";
		
		public const string address1_longitude = "address1_longitude";
		
		public const string address1_name = "address1_name";
		
		public const string address1_postalcode = "address1_postalcode";
		
		public const string address1_postofficebox = "address1_postofficebox";
		
		public const string address1_primarycontactname = "address1_primarycontactname";
		
		public const string address1_shippingmethodcode = "address1_shippingmethodcode";
		
		public const string address1_stateorprovince = "address1_stateorprovince";
		
		public const string address1_telephone1 = "address1_telephone1";
		
		public const string address1_telephone2 = "address1_telephone2";
		
		public const string address1_telephone3 = "address1_telephone3";
		
		public const string address1_upszone = "address1_upszone";
		
		public const string address1_utcoffset = "address1_utcoffset";
		
		public const string address2_addressid = "address2_addressid";
		
		public const string address2_addresstypecode = "address2_addresstypecode";
		
		public const string address2_city = "address2_city";
		
		public const string address2_composite = "address2_composite";
		
		public const string address2_country = "address2_country";
		
		public const string address2_county = "address2_county";
		
		public const string address2_fax = "address2_fax";
		
		public const string address2_freighttermscode = "address2_freighttermscode";
		
		public const string address2_latitude = "address2_latitude";
		
		public const string address2_line1 = "address2_line1";
		
		public const string address2_line2 = "address2_line2";
		
		public const string address2_line3 = "address2_line3";
		
		public const string address2_longitude = "address2_longitude";
		
		public const string address2_name = "address2_name";
		
		public const string address2_postalcode = "address2_postalcode";
		
		public const string address2_postofficebox = "address2_postofficebox";
		
		public const string address2_primarycontactname = "address2_primarycontactname";
		
		public const string address2_shippingmethodcode = "address2_shippingmethodcode";
		
		public const string address2_stateorprovince = "address2_stateorprovince";
		
		public const string address2_telephone1 = "address2_telephone1";
		
		public const string address2_telephone2 = "address2_telephone2";
		
		public const string address2_telephone3 = "address2_telephone3";
		
		public const string address2_upszone = "address2_upszone";
		
		public const string address2_utcoffset = "address2_utcoffset";
		
		public const string aging30 = "aging30";
		
		public const string aging30_base = "aging30_base";
		
		public const string aging60 = "aging60";
		
		public const string aging60_base = "aging60_base";
		
		public const string aging90 = "aging90";
		
		public const string aging90_base = "aging90_base";
		
		public const string businesstypecode = "businesstypecode";
		
		public const string createdby = "createdby";
		
		public const string createdbyexternalparty = "createdbyexternalparty";
		
		public const string createdon = "createdon";
		
		public const string createdonbehalfby = "createdonbehalfby";
		
		public const string creditlimit = "creditlimit";
		
		public const string creditlimit_base = "creditlimit_base";
		
		public const string creditonhold = "creditonhold";
		
		public const string customersizecode = "customersizecode";
		
		public const string customertypecode = "customertypecode";
		
		public const string defaultpricelevelid = "defaultpricelevelid";
		
		public const string description = "description";
		
		public const string donotbulkemail = "donotbulkemail";
		
		public const string donotbulkpostalmail = "donotbulkpostalmail";
		
		public const string donotemail = "donotemail";
		
		public const string donotfax = "donotfax";
		
		public const string donotphone = "donotphone";
		
		public const string donotpostalmail = "donotpostalmail";
		
		public const string donotsendmm = "donotsendmm";
		
		public const string emailaddress1 = "emailaddress1";
		
		public const string emailaddress2 = "emailaddress2";
		
		public const string emailaddress3 = "emailaddress3";
		
		public const string entityimage = "entityimage";
		
		public const string entityimage_timestamp = "entityimage_timestamp";
		
		public const string entityimage_url = "entityimage_url";
		
		public const string entityimageid = "entityimageid";
		
		public const string exchangerate = "exchangerate";
		
		public const string fax = "fax";
		
		public const string followemail = "followemail";
		
		public const string ftpsiteurl = "ftpsiteurl";
		
		public const string importsequencenumber = "importsequencenumber";
		
		public const string industrycode = "industrycode";
		
		public const string lastonholdtime = "lastonholdtime";
		
		public const string lastusedincampaign = "lastusedincampaign";
		
		public const string marketcap = "marketcap";
		
		public const string marketcap_base = "marketcap_base";
		
		public const string marketingonly = "marketingonly";
		
		public const string masterid = "masterid";
		
		public const string merged = "merged";
		
		public const string modifiedby = "modifiedby";
		
		public const string modifiedbyexternalparty = "modifiedbyexternalparty";
		
		public const string modifiedon = "modifiedon";
		
		public const string modifiedonbehalfby = "modifiedonbehalfby";
		
		public const string name = "name";
		
		public const string numberofemployees = "numberofemployees";
		
		public const string onholdtime = "onholdtime";
		
		public const string opendeals = "opendeals";
		
		public const string opendeals_date = "opendeals_date";
		
		public const string opendeals_state = "opendeals_state";
		
		public const string openrevenue = "openrevenue";
		
		public const string openrevenue_base = "openrevenue_base";
		
		public const string openrevenue_date = "openrevenue_date";
		
		public const string openrevenue_state = "openrevenue_state";
		
		public const string originatingleadid = "originatingleadid";
		
		public const string overriddencreatedon = "overriddencreatedon";
		
		public const string ownerid = "ownerid";
		
		public const string ownershipcode = "ownershipcode";
		
		public const string owningbusinessunit = "owningbusinessunit";
		
		public const string owningteam = "owningteam";
		
		public const string owninguser = "owninguser";
		
		public const string parentaccountid = "parentaccountid";
		
		public const string participatesinworkflow = "participatesinworkflow";
		
		public const string paymenttermscode = "paymenttermscode";
		
		public const string preferredappointmentdaycode = "preferredappointmentdaycode";
		
		public const string preferredappointmenttimecode = "preferredappointmenttimecode";
		
		public const string preferredcontactmethodcode = "preferredcontactmethodcode";
		
		public const string preferredequipmentid = "preferredequipmentid";
		
		public const string preferredserviceid = "preferredserviceid";
		
		public const string preferredsystemuserid = "preferredsystemuserid";
		
		public const string primarycontactid = "primarycontactid";
		
		public const string primarysatoriid = "primarysatoriid";
		
		public const string primarytwitterid = "primarytwitterid";
		
		public const string processid = "processid";
		
		public const string revenue = "revenue";
		
		public const string revenue_base = "revenue_base";
		
		public const string sharesoutstanding = "sharesoutstanding";
		
		public const string shippingmethodcode = "shippingmethodcode";
		
		public const string sic = "sic";
		
		public const string slaid = "slaid";
		
		public const string slainvokedid = "slainvokedid";
		
		public const string stageid = "stageid";
		
		public const string statecode = "statecode";
		
		public const string statuscode = "statuscode";
		
		public const string stockexchange = "stockexchange";
		
		public const string teamsfollowed = "teamsfollowed";
		
		public const string telephone1 = "telephone1";
		
		public const string telephone2 = "telephone2";
		
		public const string telephone3 = "telephone3";
		
		public const string territorycode = "territorycode";
		
		public const string territoryid = "territoryid";
		
		public const string tickersymbol = "tickersymbol";
		
		public const string timespentbymeonemailandmeetings = "timespentbymeonemailandmeetings";
		
		public const string timezoneruleversionnumber = "timezoneruleversionnumber";
		
		public const string transactioncurrencyid = "transactioncurrencyid";
		
		public const string traversedpath = "traversedpath";
		
		public const string utcconversiontimezonecode = "utcconversiontimezonecode";
		
		public const string versionnumber = "versionnumber";
		
		public const string websiteurl = "websiteurl";
		
		public const string yominame = "yominame";
	}
	#endregion
	
	#region 
	static
	/// <summary>
	/// Person with whom a business unit has a relationship, such as customer, supplier, and colleague.
	/// </summary>
	public partial class ContactLogicalNames
	{
		
		public const string accountid = "accountid";
		
		public const string accountrolecode = "accountrolecode";
		
		public const string address1_addressid = "address1_addressid";
		
		public const string address1_addresstypecode = "address1_addresstypecode";
		
		public const string address1_city = "address1_city";
		
		public const string address1_composite = "address1_composite";
		
		public const string address1_country = "address1_country";
		
		public const string address1_county = "address1_county";
		
		public const string address1_fax = "address1_fax";
		
		public const string address1_freighttermscode = "address1_freighttermscode";
		
		public const string address1_latitude = "address1_latitude";
		
		public const string address1_line1 = "address1_line1";
		
		public const string address1_line2 = "address1_line2";
		
		public const string address1_line3 = "address1_line3";
		
		public const string address1_longitude = "address1_longitude";
		
		public const string address1_name = "address1_name";
		
		public const string address1_postalcode = "address1_postalcode";
		
		public const string address1_postofficebox = "address1_postofficebox";
		
		public const string address1_primarycontactname = "address1_primarycontactname";
		
		public const string address1_shippingmethodcode = "address1_shippingmethodcode";
		
		public const string address1_stateorprovince = "address1_stateorprovince";
		
		public const string address1_telephone1 = "address1_telephone1";
		
		public const string address1_telephone2 = "address1_telephone2";
		
		public const string address1_telephone3 = "address1_telephone3";
		
		public const string address1_upszone = "address1_upszone";
		
		public const string address1_utcoffset = "address1_utcoffset";
		
		public const string address2_addressid = "address2_addressid";
		
		public const string address2_addresstypecode = "address2_addresstypecode";
		
		public const string address2_city = "address2_city";
		
		public const string address2_composite = "address2_composite";
		
		public const string address2_country = "address2_country";
		
		public const string address2_county = "address2_county";
		
		public const string address2_fax = "address2_fax";
		
		public const string address2_freighttermscode = "address2_freighttermscode";
		
		public const string address2_latitude = "address2_latitude";
		
		public const string address2_line1 = "address2_line1";
		
		public const string address2_line2 = "address2_line2";
		
		public const string address2_line3 = "address2_line3";
		
		public const string address2_longitude = "address2_longitude";
		
		public const string address2_name = "address2_name";
		
		public const string address2_postalcode = "address2_postalcode";
		
		public const string address2_postofficebox = "address2_postofficebox";
		
		public const string address2_primarycontactname = "address2_primarycontactname";
		
		public const string address2_shippingmethodcode = "address2_shippingmethodcode";
		
		public const string address2_stateorprovince = "address2_stateorprovince";
		
		public const string address2_telephone1 = "address2_telephone1";
		
		public const string address2_telephone2 = "address2_telephone2";
		
		public const string address2_telephone3 = "address2_telephone3";
		
		public const string address2_upszone = "address2_upszone";
		
		public const string address2_utcoffset = "address2_utcoffset";
		
		public const string address3_addressid = "address3_addressid";
		
		public const string address3_addresstypecode = "address3_addresstypecode";
		
		public const string address3_city = "address3_city";
		
		public const string address3_composite = "address3_composite";
		
		public const string address3_country = "address3_country";
		
		public const string address3_county = "address3_county";
		
		public const string address3_fax = "address3_fax";
		
		public const string address3_freighttermscode = "address3_freighttermscode";
		
		public const string address3_latitude = "address3_latitude";
		
		public const string address3_line1 = "address3_line1";
		
		public const string address3_line2 = "address3_line2";
		
		public const string address3_line3 = "address3_line3";
		
		public const string address3_longitude = "address3_longitude";
		
		public const string address3_name = "address3_name";
		
		public const string address3_postalcode = "address3_postalcode";
		
		public const string address3_postofficebox = "address3_postofficebox";
		
		public const string address3_primarycontactname = "address3_primarycontactname";
		
		public const string address3_shippingmethodcode = "address3_shippingmethodcode";
		
		public const string address3_stateorprovince = "address3_stateorprovince";
		
		public const string address3_telephone1 = "address3_telephone1";
		
		public const string address3_telephone2 = "address3_telephone2";
		
		public const string address3_telephone3 = "address3_telephone3";
		
		public const string address3_upszone = "address3_upszone";
		
		public const string address3_utcoffset = "address3_utcoffset";
		
		public const string aging30 = "aging30";
		
		public const string aging30_base = "aging30_base";
		
		public const string aging60 = "aging60";
		
		public const string aging60_base = "aging60_base";
		
		public const string aging90 = "aging90";
		
		public const string aging90_base = "aging90_base";
		
		public const string anniversary = "anniversary";
		
		public const string annualincome = "annualincome";
		
		public const string annualincome_base = "annualincome_base";
		
		public const string assistantname = "assistantname";
		
		public const string assistantphone = "assistantphone";
		
		public const string birthdate = "birthdate";
		
		public const string business2 = "business2";
		
		public const string businesscard = "businesscard";
		
		public const string businesscardattributes = "businesscardattributes";
		
		public const string callback = "callback";
		
		public const string childrensnames = "childrensnames";
		
		public const string company = "company";
		
		public const string contactid = "contactid";
		
		public const string createdby = "createdby";
		
		public const string createdbyexternalparty = "createdbyexternalparty";
		
		public const string createdon = "createdon";
		
		public const string createdonbehalfby = "createdonbehalfby";
		
		public const string creditlimit = "creditlimit";
		
		public const string creditlimit_base = "creditlimit_base";
		
		public const string creditonhold = "creditonhold";
		
		public const string customersizecode = "customersizecode";
		
		public const string customertypecode = "customertypecode";
		
		public const string defaultpricelevelid = "defaultpricelevelid";
		
		public const string department = "department";
		
		public const string description = "description";
		
		public const string donotbulkemail = "donotbulkemail";
		
		public const string donotbulkpostalmail = "donotbulkpostalmail";
		
		public const string donotemail = "donotemail";
		
		public const string donotfax = "donotfax";
		
		public const string donotphone = "donotphone";
		
		public const string donotpostalmail = "donotpostalmail";
		
		public const string donotsendmm = "donotsendmm";
		
		public const string educationcode = "educationcode";
		
		public const string emailaddress1 = "emailaddress1";
		
		public const string emailaddress2 = "emailaddress2";
		
		public const string emailaddress3 = "emailaddress3";
		
		public const string employeeid = "employeeid";
		
		public const string entityimage = "entityimage";
		
		public const string entityimage_timestamp = "entityimage_timestamp";
		
		public const string entityimage_url = "entityimage_url";
		
		public const string entityimageid = "entityimageid";
		
		public const string exchangerate = "exchangerate";
		
		public const string externaluseridentifier = "externaluseridentifier";
		
		public const string familystatuscode = "familystatuscode";
		
		public const string fax = "fax";
		
		public const string firstname = "firstname";
		
		public const string followemail = "followemail";
		
		public const string ftpsiteurl = "ftpsiteurl";
		
		public const string fullname = "fullname";
		
		public const string gendercode = "gendercode";
		
		public const string governmentid = "governmentid";
		
		public const string haschildrencode = "haschildrencode";
		
		public const string home2 = "home2";
		
		public const string importsequencenumber = "importsequencenumber";
		
		public const string isbackofficecustomer = "isbackofficecustomer";
		
		public const string jobtitle = "jobtitle";
		
		public const string lastname = "lastname";
		
		public const string lastonholdtime = "lastonholdtime";
		
		public const string lastusedincampaign = "lastusedincampaign";
		
		public const string leadsourcecode = "leadsourcecode";
		
		public const string managername = "managername";
		
		public const string managerphone = "managerphone";
		
		public const string marketingonly = "marketingonly";
		
		public const string masterid = "masterid";
		
		public const string merged = "merged";
		
		public const string middlename = "middlename";
		
		public const string mobilephone = "mobilephone";
		
		public const string modifiedby = "modifiedby";
		
		public const string modifiedbyexternalparty = "modifiedbyexternalparty";
		
		public const string modifiedon = "modifiedon";
		
		public const string modifiedonbehalfby = "modifiedonbehalfby";
		
		public const string msdyn_gdproptout = "msdyn_gdproptout";
		
		public const string msdyn_orgchangestatus = "msdyn_orgchangestatus";
		
		public const string nickname = "nickname";
		
		public const string numberofchildren = "numberofchildren";
		
		public const string onholdtime = "onholdtime";
		
		public const string originatingleadid = "originatingleadid";
		
		public const string overriddencreatedon = "overriddencreatedon";
		
		public const string ownerid = "ownerid";
		
		public const string owningbusinessunit = "owningbusinessunit";
		
		public const string owningteam = "owningteam";
		
		public const string owninguser = "owninguser";
		
		public const string pager = "pager";
		
		public const string parentcontactid = "parentcontactid";
		
		public const string parentcustomerid = "parentcustomerid";
		
		public const string participatesinworkflow = "participatesinworkflow";
		
		public const string paymenttermscode = "paymenttermscode";
		
		public const string preferredappointmentdaycode = "preferredappointmentdaycode";
		
		public const string preferredappointmenttimecode = "preferredappointmenttimecode";
		
		public const string preferredcontactmethodcode = "preferredcontactmethodcode";
		
		public const string preferredequipmentid = "preferredequipmentid";
		
		public const string preferredserviceid = "preferredserviceid";
		
		public const string preferredsystemuserid = "preferredsystemuserid";
		
		public const string processid = "processid";
		
		public const string salutation = "salutation";
		
		public const string shippingmethodcode = "shippingmethodcode";
		
		public const string slaid = "slaid";
		
		public const string slainvokedid = "slainvokedid";
		
		public const string spousesname = "spousesname";
		
		public const string stageid = "stageid";
		
		public const string statecode = "statecode";
		
		public const string statuscode = "statuscode";
		
		public const string subscriptionid = "subscriptionid";
		
		public const string suffix = "suffix";
		
		public const string teamsfollowed = "teamsfollowed";
		
		public const string telephone1 = "telephone1";
		
		public const string telephone2 = "telephone2";
		
		public const string telephone3 = "telephone3";
		
		public const string territorycode = "territorycode";
		
		public const string timespentbymeonemailandmeetings = "timespentbymeonemailandmeetings";
		
		public const string timezoneruleversionnumber = "timezoneruleversionnumber";
		
		public const string transactioncurrencyid = "transactioncurrencyid";
		
		public const string traversedpath = "traversedpath";
		
		public const string utcconversiontimezonecode = "utcconversiontimezonecode";
		
		public const string versionnumber = "versionnumber";
		
		public const string websiteurl = "websiteurl";
		
		public const string yomifirstname = "yomifirstname";
		
		public const string yomifullname = "yomifullname";
		
		public const string yomilastname = "yomilastname";
		
		public const string yomimiddlename = "yomimiddlename";
	}
	#endregion
}
