//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoC.Workflow.Entities
{
	
	
	#region 
	static
	/// <summary>
	/// Active path associated with every Business Process Flow instance
	/// </summary>
	public partial class BusinessProcessFlowInstanceLogicalNames
	{
		
		public const string activestagestartedon = "activestagestartedon";
		
		public const string businessprocessflowinstanceid = "businessprocessflowinstanceid";
		
		public const string completedon = "completedon";
		
		public const string createdby = "createdby";
		
		public const string createdon = "createdon";
		
		public const string createdonbehalfby = "createdonbehalfby";
		
		public const string entity1id = "entity1id";
		
		public const string entity1objecttypecode = "entity1objecttypecode";
		
		public const string entity2id = "entity2id";
		
		public const string entity2objecttypecode = "entity2objecttypecode";
		
		public const string entity3id = "entity3id";
		
		public const string entity3objecttypecode = "entity3objecttypecode";
		
		public const string entity4id = "entity4id";
		
		public const string entity4objecttypecode = "entity4objecttypecode";
		
		public const string entity5id = "entity5id";
		
		public const string entity5objecttypecode = "entity5objecttypecode";
		
		public const string modifiedby = "modifiedby";
		
		public const string modifiedon = "modifiedon";
		
		public const string modifiedonbehalfby = "modifiedonbehalfby";
		
		public const string name = "name";
		
		public const string processid = "processid";
		
		public const string processstageid = "processstageid";
		
		public const string statecode = "statecode";
		
		public const string statuscode = "statuscode";
		
		public const string traversedpath = "traversedpath";
		
		public const string versionnumber = "versionnumber";
	}
	#endregion
	
	#region 
	static
	/// <summary>
	/// Calendar used by the scheduling system to define when an appointment or activity is to occur.
	/// </summary>
	public partial class CalendarLogicalNames
	{
		
		public const string businessunitid = "businessunitid";
		
		public const string calendarid = "calendarid";
		
		public const string createdby = "createdby";
		
		public const string createdon = "createdon";
		
		public const string createdonbehalfby = "createdonbehalfby";
		
		public const string description = "description";
		
		public const string holidayschedulecalendarid = "holidayschedulecalendarid";
		
		public const string isshared = "isshared";
		
		public const string modifiedby = "modifiedby";
		
		public const string modifiedon = "modifiedon";
		
		public const string modifiedonbehalfby = "modifiedonbehalfby";
		
		public const string name = "name";
		
		public const string organizationid = "organizationid";
		
		public const string primaryuserid = "primaryuserid";
		
		public const string type = "type";
		
		public const string versionnumber = "versionnumber";
		
		public const string calendarrules = "calendarrules";
	}
	#endregion
	
	#region 
	static
	/// <summary>
	/// Defines free/busy times for a service and for resources or resource groups, such as working, non-working, vacation, and blocked.
	/// </summary>
	public partial class CalendarRuleLogicalNames
	{
		
		public const string businessunitid = "businessunitid";
		
		public const string calendarid = "calendarid";
		
		public const string calendarruleid = "calendarruleid";
		
		public const string createdby = "createdby";
		
		public const string createdon = "createdon";
		
		public const string createdonbehalfby = "createdonbehalfby";
		
		public const string description = "description";
		
		public const string duration = "duration";
		
		public const string effectiveintervalend = "effectiveintervalend";
		
		public const string effectiveintervalstart = "effectiveintervalstart";
		
		public const string effort = "effort";
		
		public const string endtime = "endtime";
		
		public const string extentcode = "extentcode";
		
		public const string groupdesignator = "groupdesignator";
		
		public const string innercalendarid = "innercalendarid";
		
		public const string ismodified = "ismodified";
		
		public const string isselected = "isselected";
		
		public const string issimple = "issimple";
		
		public const string isvaried = "isvaried";
		
		public const string modifiedby = "modifiedby";
		
		public const string modifiedon = "modifiedon";
		
		public const string modifiedonbehalfby = "modifiedonbehalfby";
		
		public const string name = "name";
		
		public const string offset = "offset";
		
		public const string organizationid = "organizationid";
		
		public const string pattern = "pattern";
		
		public const string rank = "rank";
		
		public const string serviceid = "serviceid";
		
		public const string starttime = "starttime";
		
		public const string subcode = "subcode";
		
		public const string timecode = "timecode";
		
		public const string timezonecode = "timezonecode";
		
		public const string versionnumber = "versionnumber";
	}
	#endregion
	
	#region 
	static
	/// <summary>
	/// Activity that is delivered using email protocols.
	/// </summary>
	public partial class EmailLogicalNames
	{
		
		public const string activityadditionalparams = "activityadditionalparams";
		
		public const string activityid = "activityid";
		
		public const string activitytypecode = "activitytypecode";
		
		public const string actualdurationminutes = "actualdurationminutes";
		
		public const string actualend = "actualend";
		
		public const string actualstart = "actualstart";
		
		public const string attachmentcount = "attachmentcount";
		
		public const string attachmentopencount = "attachmentopencount";
		
		public const string baseconversationindexhash = "baseconversationindexhash";
		
		public const string bcc = "bcc";
		
		public const string category = "category";
		
		public const string cc = "cc";
		
		public const string compressed = "compressed";
		
		public const string conversationindex = "conversationindex";
		
		public const string conversationtrackingid = "conversationtrackingid";
		
		public const string correlationmethod = "correlationmethod";
		
		public const string createdby = "createdby";
		
		public const string createdon = "createdon";
		
		public const string createdonbehalfby = "createdonbehalfby";
		
		public const string delayedemailsendtime = "delayedemailsendtime";
		
		public const string deliveryattempts = "deliveryattempts";
		
		public const string deliveryprioritycode = "deliveryprioritycode";
		
		public const string deliveryreceiptrequested = "deliveryreceiptrequested";
		
		public const string description = "description";
		
		public const string directioncode = "directioncode";
		
		public const string emailreminderexpirytime = "emailreminderexpirytime";
		
		public const string emailreminderstatus = "emailreminderstatus";
		
		public const string emailremindertext = "emailremindertext";
		
		public const string emailremindertype = "emailremindertype";
		
		public const string emailsender = "emailsender";
		
		public const string emailtrackingid = "emailtrackingid";
		
		public const string exchangerate = "exchangerate";
		
		public const string followemailuserpreference = "followemailuserpreference";
		
		public const string from = "from";
		
		public const string importsequencenumber = "importsequencenumber";
		
		public const string inreplyto = "inreplyto";
		
		public const string isbilled = "isbilled";
		
		public const string isemailfollowed = "isemailfollowed";
		
		public const string isemailreminderset = "isemailreminderset";
		
		public const string isregularactivity = "isregularactivity";
		
		public const string isunsafe = "isunsafe";
		
		public const string isworkflowcreated = "isworkflowcreated";
		
		public const string lastonholdtime = "lastonholdtime";
		
		public const string lastopenedtime = "lastopenedtime";
		
		public const string linksclickedcount = "linksclickedcount";
		
		public const string messageid = "messageid";
		
		public const string messageiddupcheck = "messageiddupcheck";
		
		public const string mimetype = "mimetype";
		
		public const string modifiedby = "modifiedby";
		
		public const string modifiedon = "modifiedon";
		
		public const string modifiedonbehalfby = "modifiedonbehalfby";
		
		public const string notifications = "notifications";
		
		public const string onholdtime = "onholdtime";
		
		public const string opencount = "opencount";
		
		public const string overriddencreatedon = "overriddencreatedon";
		
		public const string ownerid = "ownerid";
		
		public const string owningbusinessunit = "owningbusinessunit";
		
		public const string owningteam = "owningteam";
		
		public const string owninguser = "owninguser";
		
		public const string parentactivityid = "parentactivityid";
		
		public const string postponeemailprocessinguntil = "postponeemailprocessinguntil";
		
		public const string prioritycode = "prioritycode";
		
		public const string processid = "processid";
		
		public const string readreceiptrequested = "readreceiptrequested";
		
		public const string regardingobjectid = "regardingobjectid";
		
		public const string reminderactioncardid = "reminderactioncardid";
		
		public const string replycount = "replycount";
		
		public const string scheduleddurationminutes = "scheduleddurationminutes";
		
		public const string scheduledend = "scheduledend";
		
		public const string scheduledstart = "scheduledstart";
		
		public const string sender = "sender";
		
		public const string sendermailboxid = "sendermailboxid";
		
		public const string sendersaccount = "sendersaccount";
		
		public const string senton = "senton";
		
		public const string serviceid = "serviceid";
		
		public const string slaid = "slaid";
		
		public const string slainvokedid = "slainvokedid";
		
		public const string sortdate = "sortdate";
		
		public const string stageid = "stageid";
		
		public const string statecode = "statecode";
		
		public const string statuscode = "statuscode";
		
		public const string subcategory = "subcategory";
		
		public const string subject = "subject";
		
		public const string submittedby = "submittedby";
		
		public const string templateid = "templateid";
		
		public const string timezoneruleversionnumber = "timezoneruleversionnumber";
		
		public const string to = "to";
		
		public const string torecipients = "torecipients";
		
		public const string trackingtoken = "trackingtoken";
		
		public const string transactioncurrencyid = "transactioncurrencyid";
		
		public const string traversedpath = "traversedpath";
		
		public const string utcconversiontimezonecode = "utcconversiontimezonecode";
		
		public const string versionnumber = "versionnumber";
	}
	#endregion
	
	#region 
	static
	/// <summary>
	/// Stage associated with a process.
	/// </summary>
	public partial class ProcessStageLogicalNames
	{
		
		public const string clientdata = "clientdata";
		
		public const string connector = "connector";
		
		public const string istrigger = "istrigger";
		
		public const string operationid = "operationid";
		
		public const string operationkind = "operationkind";
		
		public const string operationtype = "operationtype";
		
		public const string ownerid = "ownerid";
		
		public const string owningbusinessunit = "owningbusinessunit";
		
		public const string primaryentitytypecode = "primaryentitytypecode";
		
		public const string processid = "processid";
		
		public const string processstageid = "processstageid";
		
		public const string stagecategory = "stagecategory";
		
		public const string stagename = "stagename";
		
		public const string versionnumber = "versionnumber";
	}
	#endregion
	
	#region 
	static
	/// <summary>
	/// Person with access to the Microsoft CRM system and who owns objects in the Microsoft CRM database.
	/// </summary>
	public partial class SystemUserLogicalNames
	{
		
		public const string accessmode = "accessmode";
		
		public const string address1_addressid = "address1_addressid";
		
		public const string address1_addresstypecode = "address1_addresstypecode";
		
		public const string address1_city = "address1_city";
		
		public const string address1_composite = "address1_composite";
		
		public const string address1_country = "address1_country";
		
		public const string address1_county = "address1_county";
		
		public const string address1_fax = "address1_fax";
		
		public const string address1_latitude = "address1_latitude";
		
		public const string address1_line1 = "address1_line1";
		
		public const string address1_line2 = "address1_line2";
		
		public const string address1_line3 = "address1_line3";
		
		public const string address1_longitude = "address1_longitude";
		
		public const string address1_name = "address1_name";
		
		public const string address1_postalcode = "address1_postalcode";
		
		public const string address1_postofficebox = "address1_postofficebox";
		
		public const string address1_shippingmethodcode = "address1_shippingmethodcode";
		
		public const string address1_stateorprovince = "address1_stateorprovince";
		
		public const string address1_telephone1 = "address1_telephone1";
		
		public const string address1_telephone2 = "address1_telephone2";
		
		public const string address1_telephone3 = "address1_telephone3";
		
		public const string address1_upszone = "address1_upszone";
		
		public const string address1_utcoffset = "address1_utcoffset";
		
		public const string address2_addressid = "address2_addressid";
		
		public const string address2_addresstypecode = "address2_addresstypecode";
		
		public const string address2_city = "address2_city";
		
		public const string address2_composite = "address2_composite";
		
		public const string address2_country = "address2_country";
		
		public const string address2_county = "address2_county";
		
		public const string address2_fax = "address2_fax";
		
		public const string address2_latitude = "address2_latitude";
		
		public const string address2_line1 = "address2_line1";
		
		public const string address2_line2 = "address2_line2";
		
		public const string address2_line3 = "address2_line3";
		
		public const string address2_longitude = "address2_longitude";
		
		public const string address2_name = "address2_name";
		
		public const string address2_postalcode = "address2_postalcode";
		
		public const string address2_postofficebox = "address2_postofficebox";
		
		public const string address2_shippingmethodcode = "address2_shippingmethodcode";
		
		public const string address2_stateorprovince = "address2_stateorprovince";
		
		public const string address2_telephone1 = "address2_telephone1";
		
		public const string address2_telephone2 = "address2_telephone2";
		
		public const string address2_telephone3 = "address2_telephone3";
		
		public const string address2_upszone = "address2_upszone";
		
		public const string address2_utcoffset = "address2_utcoffset";
		
		public const string applicationid = "applicationid";
		
		public const string applicationiduri = "applicationiduri";
		
		public const string azureactivedirectoryobjectid = "azureactivedirectoryobjectid";
		
		public const string businessunitid = "businessunitid";
		
		public const string calendarid = "calendarid";
		
		public const string caltype = "caltype";
		
		public const string createdby = "createdby";
		
		public const string createdon = "createdon";
		
		public const string createdonbehalfby = "createdonbehalfby";
		
		public const string defaultfilterspopulated = "defaultfilterspopulated";
		
		public const string defaultmailbox = "defaultmailbox";
		
		public const string defaultodbfoldername = "defaultodbfoldername";
		
		public const string disabledreason = "disabledreason";
		
		public const string displayinserviceviews = "displayinserviceviews";
		
		public const string domainname = "domainname";
		
		public const string emailrouteraccessapproval = "emailrouteraccessapproval";
		
		public const string employeeid = "employeeid";
		
		public const string entityimage = "entityimage";
		
		public const string entityimage_timestamp = "entityimage_timestamp";
		
		public const string entityimage_url = "entityimage_url";
		
		public const string entityimageid = "entityimageid";
		
		public const string exchangerate = "exchangerate";
		
		public const string firstname = "firstname";
		
		public const string fullname = "fullname";
		
		public const string governmentid = "governmentid";
		
		public const string homephone = "homephone";
		
		public const string identityid = "identityid";
		
		public const string importsequencenumber = "importsequencenumber";
		
		public const string incomingemaildeliverymethod = "incomingemaildeliverymethod";
		
		public const string internalemailaddress = "internalemailaddress";
		
		public const string invitestatuscode = "invitestatuscode";
		
		public const string isdisabled = "isdisabled";
		
		public const string isemailaddressapprovedbyo365admin = "isemailaddressapprovedbyo365admin";
		
		public const string isintegrationuser = "isintegrationuser";
		
		public const string islicensed = "islicensed";
		
		public const string issyncwithdirectory = "issyncwithdirectory";
		
		public const string jobtitle = "jobtitle";
		
		public const string lastname = "lastname";
		
		public const string middlename = "middlename";
		
		public const string mobilealertemail = "mobilealertemail";
		
		public const string mobileofflineprofileid = "mobileofflineprofileid";
		
		public const string mobilephone = "mobilephone";
		
		public const string modifiedby = "modifiedby";
		
		public const string modifiedon = "modifiedon";
		
		public const string modifiedonbehalfby = "modifiedonbehalfby";
		
		public const string msdyn_gdproptout = "msdyn_gdproptout";
		
		public const string nickname = "nickname";
		
		public const string organizationid = "organizationid";
		
		public const string outgoingemaildeliverymethod = "outgoingemaildeliverymethod";
		
		public const string overriddencreatedon = "overriddencreatedon";
		
		public const string parentsystemuserid = "parentsystemuserid";
		
		public const string passporthi = "passporthi";
		
		public const string passportlo = "passportlo";
		
		public const string personalemailaddress = "personalemailaddress";
		
		public const string photourl = "photourl";
		
		public const string positionid = "positionid";
		
		public const string preferredaddresscode = "preferredaddresscode";
		
		public const string preferredemailcode = "preferredemailcode";
		
		public const string preferredphonecode = "preferredphonecode";
		
		public const string processid = "processid";
		
		public const string queueid = "queueid";
		
		public const string salutation = "salutation";
		
		public const string setupuser = "setupuser";
		
		public const string sharepointemailaddress = "sharepointemailaddress";
		
		public const string siteid = "siteid";
		
		public const string skills = "skills";
		
		public const string sp_extension = "sp_extension";
		
		public const string stageid = "stageid";
		
		public const string swf_primaryteamid = "swf_primaryteamid";
		
		public const string systemuserid = "systemuserid";
		
		public const string territoryid = "territoryid";
		
		public const string timezoneruleversionnumber = "timezoneruleversionnumber";
		
		public const string title = "title";
		
		public const string transactioncurrencyid = "transactioncurrencyid";
		
		public const string traversedpath = "traversedpath";
		
		public const string userlicensetype = "userlicensetype";
		
		public const string userpuid = "userpuid";
		
		public const string utcconversiontimezonecode = "utcconversiontimezonecode";
		
		public const string versionnumber = "versionnumber";
		
		public const string windowsliveid = "windowsliveid";
		
		public const string yammeremailaddress = "yammeremailaddress";
		
		public const string yammeruserid = "yammeruserid";
		
		public const string yomifirstname = "yomifirstname";
		
		public const string yomifullname = "yomifullname";
		
		public const string yomilastname = "yomilastname";
		
		public const string yomimiddlename = "yomimiddlename";
	}
	#endregion
	
	#region 
	static
	/// <summary>
	/// Collection of system users that routinely collaborate. Teams can be used to simplify record sharing and provide team members with common access to organization data when team members belong to different Business Units.
	/// </summary>
	public partial class TeamLogicalNames
	{
		
		public const string administratorid = "administratorid";
		
		public const string azureactivedirectoryobjectid = "azureactivedirectoryobjectid";
		
		public const string businessunitid = "businessunitid";
		
		public const string createdby = "createdby";
		
		public const string createdon = "createdon";
		
		public const string createdonbehalfby = "createdonbehalfby";
		
		public const string description = "description";
		
		public const string emailaddress = "emailaddress";
		
		public const string exchangerate = "exchangerate";
		
		public const string importsequencenumber = "importsequencenumber";
		
		public const string isdefault = "isdefault";
		
		public const string modifiedby = "modifiedby";
		
		public const string modifiedon = "modifiedon";
		
		public const string modifiedonbehalfby = "modifiedonbehalfby";
		
		public const string name = "name";
		
		public const string organizationid = "organizationid";
		
		public const string overriddencreatedon = "overriddencreatedon";
		
		public const string processid = "processid";
		
		public const string queueid = "queueid";
		
		public const string regardingobjectid = "regardingobjectid";
		
		public const string stageid = "stageid";
		
		public const string swf_emailqueueid = "swf_emailqueueid";
		
		public const string systemmanaged = "systemmanaged";
		
		public const string teamid = "teamid";
		
		public const string teamtemplateid = "teamtemplateid";
		
		public const string teamtype = "teamtype";
		
		public const string transactioncurrencyid = "transactioncurrencyid";
		
		public const string traversedpath = "traversedpath";
		
		public const string versionnumber = "versionnumber";
		
		public const string yominame = "yominame";
	}
	#endregion
	
	#region 
	static
	/// <summary>
	/// 
	/// </summary>
	public partial class TeamMembershipLogicalNames
	{
		
		public const string systemuserid = "systemuserid";
		
		public const string teamid = "teamid";
		
		public const string teammembershipid = "teammembershipid";
		
		public const string versionnumber = "versionnumber";
	}
	#endregion
	
	#region 
	static
	/// <summary>
	/// Template for an email message that contains the standard attributes of an email message.
	/// </summary>
	public partial class TemplateLogicalNames
	{
		
		public const string body = "body";
		
		public const string componentstate = "componentstate";
		
		public const string createdby = "createdby";
		
		public const string createdon = "createdon";
		
		public const string createdonbehalfby = "createdonbehalfby";
		
		public const string description = "description";
		
		public const string generationtypecode = "generationtypecode";
		
		public const string importsequencenumber = "importsequencenumber";
		
		public const string introducedversion = "introducedversion";
		
		public const string iscustomizable = "iscustomizable";
		
		public const string ismanaged = "ismanaged";
		
		public const string ispersonal = "ispersonal";
		
		public const string isrecommended = "isrecommended";
		
		public const string languagecode = "languagecode";
		
		public const string mimetype = "mimetype";
		
		public const string modifiedby = "modifiedby";
		
		public const string modifiedon = "modifiedon";
		
		public const string modifiedonbehalfby = "modifiedonbehalfby";
		
		public const string opencount = "opencount";
		
		public const string openrate = "openrate";
		
		public const string overwritetime = "overwritetime";
		
		public const string ownerid = "ownerid";
		
		public const string owningbusinessunit = "owningbusinessunit";
		
		public const string owningteam = "owningteam";
		
		public const string owninguser = "owninguser";
		
		public const string presentationxml = "presentationxml";
		
		public const string replycount = "replycount";
		
		public const string replyrate = "replyrate";
		
		public const string solutionid = "solutionid";
		
		public const string subject = "subject";
		
		public const string subjectpresentationxml = "subjectpresentationxml";
		
		public const string templateid = "templateid";
		
		public const string templateidunique = "templateidunique";
		
		public const string templatetypecode = "templatetypecode";
		
		public const string title = "title";
		
		public const string usedcount = "usedcount";
		
		public const string versionnumber = "versionnumber";
	}
	#endregion
	
	#region 
	static
	/// <summary>
	/// Time zone definition, including name and time zone code.
	/// </summary>
	public partial class TimeZoneDefinitionLogicalNames
	{
		
		public const string bias = "bias";
		
		public const string createdby = "createdby";
		
		public const string createdon = "createdon";
		
		public const string createdonbehalfby = "createdonbehalfby";
		
		public const string daylightname = "daylightname";
		
		public const string modifiedby = "modifiedby";
		
		public const string modifiedon = "modifiedon";
		
		public const string modifiedonbehalfby = "modifiedonbehalfby";
		
		public const string organizationid = "organizationid";
		
		public const string retiredorder = "retiredorder";
		
		public const string standardname = "standardname";
		
		public const string timezonecode = "timezonecode";
		
		public const string timezonedefinitionid = "timezonedefinitionid";
		
		public const string userinterfacename = "userinterfacename";
		
		public const string versionnumber = "versionnumber";
	}
	#endregion
	
	#region 
	static
	/// <summary>
	/// Set of logical rules that define the steps necessary to automate a specific business process, task, or set of actions to be performed.
	/// </summary>
	public partial class WorkflowLogicalNames
	{
		
		public const string activeworkflowid = "activeworkflowid";
		
		public const string asyncautodelete = "asyncautodelete";
		
		public const string businessprocesstype = "businessprocesstype";
		
		public const string category = "category";
		
		public const string clientdata = "clientdata";
		
		public const string componentstate = "componentstate";
		
		public const string createdby = "createdby";
		
		public const string createdon = "createdon";
		
		public const string createdonbehalfby = "createdonbehalfby";
		
		public const string createstage = "createstage";
		
		public const string deletestage = "deletestage";
		
		public const string description = "description";
		
		public const string entityimage = "entityimage";
		
		public const string entityimage_timestamp = "entityimage_timestamp";
		
		public const string entityimage_url = "entityimage_url";
		
		public const string entityimageid = "entityimageid";
		
		public const string formid = "formid";
		
		public const string inputparameters = "inputparameters";
		
		public const string introducedversion = "introducedversion";
		
		public const string iscrmuiworkflow = "iscrmuiworkflow";
		
		public const string iscustomizable = "iscustomizable";
		
		public const string iscustomprocessingstepallowedforotherpublishers = "iscustomprocessingstepallowedforotherpublishers";
		
		public const string ismanaged = "ismanaged";
		
		public const string istransacted = "istransacted";
		
		public const string languagecode = "languagecode";
		
		public const string mode = "mode";
		
		public const string modifiedby = "modifiedby";
		
		public const string modifiedon = "modifiedon";
		
		public const string modifiedonbehalfby = "modifiedonbehalfby";
		
		public const string name = "name";
		
		public const string ondemand = "ondemand";
		
		public const string overwritetime = "overwritetime";
		
		public const string ownerid = "ownerid";
		
		public const string owningbusinessunit = "owningbusinessunit";
		
		public const string owningteam = "owningteam";
		
		public const string owninguser = "owninguser";
		
		public const string parentworkflowid = "parentworkflowid";
		
		public const string plugintypeid = "plugintypeid";
		
		public const string primaryentity = "primaryentity";
		
		public const string processorder = "processorder";
		
		public const string processroleassignment = "processroleassignment";
		
		public const string processtriggerformid = "processtriggerformid";
		
		public const string processtriggerscope = "processtriggerscope";
		
		public const string rank = "rank";
		
		public const string rendererobjecttypecode = "rendererobjecttypecode";
		
		public const string runas = "runas";
		
		public const string scope = "scope";
		
		public const string sdkmessageid = "sdkmessageid";
		
		public const string solutionid = "solutionid";
		
		public const string statecode = "statecode";
		
		public const string statuscode = "statuscode";
		
		public const string subprocess = "subprocess";
		
		public const string syncworkflowlogonfailure = "syncworkflowlogonfailure";
		
		public const string triggeroncreate = "triggeroncreate";
		
		public const string triggerondelete = "triggerondelete";
		
		public const string triggeronupdateattributelist = "triggeronupdateattributelist";
		
		public const string type = "type";
		
		public const string uidata = "uidata";
		
		public const string uiflowtype = "uiflowtype";
		
		public const string uniquename = "uniquename";
		
		public const string updatestage = "updatestage";
		
		public const string versionnumber = "versionnumber";
		
		public const string workflowid = "workflowid";
		
		public const string workflowidunique = "workflowidunique";
		
		public const string xaml = "xaml";
	}
	#endregion
}
